import { MysqlServicioRepository } from "./repository/MysqlServicioRepository";
import { GetStatsUseCase } from "../application/GetStatsUseCase";
import { GetAllServiciosUseCase } from "../application/GetAllServiciosUseCase";
import { GetServicioByIdUseCase } from "../application/GetServicioByIdUseCase";
import { AddServicioUseCase } from "../application/AddServicioUseCase";
import { UpdateServicioUseCase } from "../application/UpdateServicioUseCase";
import { GetAllTipoActividadUseCase } from "../application/GetAllTipoActividadUseCase";
import { GetAllTipoServicioUseCase } from "../application/GetAllTipoServicioUseCase";
import { GetAllEstadoServicioUseCase } from "../application/GetAllEstadoServicioUseCase";
import { GetAllUbicacionesUseCase } from "../application/GetAllUbicacionesUseCase";
import { GetAllTiposEnvioUseCase } from "../application/GetAllTiposEnvioUseCase";
import { GetStatsController } from "./controllers/GetStatsController";
import { GetAllServiciosController } from "./controllers/GetAllServiciosController";
import { GetServicioByIdController } from "./controllers/GetServicioByIdController";
import { AddServicioController } from "./controllers/AddServicioController";
import { UpdateServicioController } from "./controllers/UpdateServicioController";
import { GetAllTipoActividadController } from "./controllers/GetAllTipoActividadController";
import { GetAllTipoServicioController } from "./controllers/GetAllTipoServicioController";
import { GetAllEstadoServicioController } from "./controllers/GetAllEstadoServicioController";
import { GetPdfController } from "./controllers/GetPdfController";
import { GetCatalogosController } from "./controllers/GetCatalogosController";
import { GetServicioParaFormularioUseCase } from "../application/GetServicioParaFormularioUseCase";
import { GetServicioParaFormularioController } from "./controllers/GetServicioParaFormularioController";
import { DeleteServicioUseCase } from "../application/DeleteServicioUseCase";
import { DeleteServicioController } from "./controllers/DeleteServicioController";

export const mysqlServicioRepository = new MysqlServicioRepository();

export const getStatsUseCase = new GetStatsUseCase(mysqlServicioRepository);
export const getAllServiciosUseCase = new GetAllServiciosUseCase(mysqlServicioRepository);
export const getServicioByIdUseCase = new GetServicioByIdUseCase(mysqlServicioRepository);
export const addServicioUseCase = new AddServicioUseCase(mysqlServicioRepository);
export const updateServicioUseCase = new UpdateServicioUseCase(mysqlServicioRepository);
export const getAllTipoActividadUseCase = new GetAllTipoActividadUseCase(mysqlServicioRepository);
export const getAllTipoServicioUseCase = new GetAllTipoServicioUseCase(mysqlServicioRepository);
export const getAllEstadoServicioUseCase = new GetAllEstadoServicioUseCase(mysqlServicioRepository);
export const getAllUbicacionesUseCase = new GetAllUbicacionesUseCase(mysqlServicioRepository);
export const getAllTiposEnvioUseCase = new GetAllTiposEnvioUseCase(mysqlServicioRepository);

export const getStatsController = new GetStatsController(getStatsUseCase);
export const getAllServiciosController = new GetAllServiciosController(getAllServiciosUseCase);
export const getServicioByIdController = new GetServicioByIdController(getServicioByIdUseCase);
export const addServicioController = new AddServicioController(addServicioUseCase);
export const updateServicioController = new UpdateServicioController(updateServicioUseCase);
export const getAllTipoActividadController = new GetAllTipoActividadController(getAllTipoActividadUseCase);
export const getAllTipoServicioController = new GetAllTipoServicioController(getAllTipoServicioUseCase);
export const getAllEstadoServicioController = new GetAllEstadoServicioController(getAllEstadoServicioUseCase);
export const getCatalogosController = new GetCatalogosController(getAllUbicacionesUseCase, getAllTiposEnvioUseCase);
export const getPdfController = new GetPdfController(getServicioByIdUseCase);
export const getServicioParaFormularioUseCase = new GetServicioParaFormularioUseCase(mysqlServicioRepository);
export const getServicioParaFormularioController = new GetServicioParaFormularioController(getServicioParaFormularioUseCase);
const deleteServicioUseCase = new DeleteServicioUseCase(mysqlServicioRepository);
export const deleteServicioController = new DeleteServicioController(deleteServicioUseCase);